# Generated by Django 2.2.5 on 2020-01-28 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchqpapp', '0004_auto_20200128_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 53, 57, 815095, tzinfo=utc)),
        ),
    ]
