# Generated by Django 2.2.5 on 2020-02-14 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchqpapp', '0005_questionpaper_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 8, 55, 12, 873698, tzinfo=utc)),
        ),
    ]
