# Generated by Django 2.2.5 on 2020-02-26 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchqpapp', '0006_auto_20200214_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 8, 37, 4, 298576, tzinfo=utc)),
        ),
    ]
