# Generated by Django 2.2.5 on 2020-03-04 16:01

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchqpapp', '0007_auto_20200226_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='fileImage',
            field=models.FileField(default=django.utils.timezone.now, upload_to='searchqpapp/pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='filePdfField',
            field=models.ImageField(default=1, upload_to='searchqpapp/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 15, 59, 33, 70794, tzinfo=utc)),
        ),
    ]
