# Generated by Django 2.2.5 on 2020-03-04 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchqpapp', '0008_auto_20200304_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 16, 14, 5, 349115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='fileImage',
            field=models.ImageField(upload_to='searchqpapp/pdf'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='filePdfField',
            field=models.FileField(upload_to='searchqpapp/images'),
        ),
    ]
