# Generated by Django 2.2.5 on 2020-03-05 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchqpapp', '0010_auto_20200305_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 3, 29, 49, 885237, tzinfo=utc)),
        ),
    ]
